name: Deploy Containers

on:
    workflow_run:
        workflows: ["Build and Push to ACR"]
        types:
          - completed
    workflow_dispatch: 

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    defaults:
      run:
        working-directory: ./container
    steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.9.4

            - name: Azure Login
              uses: Azure/login@v1.5.0
              with: 
                client-id: ${{ vars.ARM_CLIENT_ID }}
                tenant-id: ${{ vars.ARM_TENANT_ID }}
                subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

            - name: Terraform Init
              env:
                ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
                ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
                ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
              run: terraform init -backend-config="backend.conf"

            - name: Terraform Plan
              env:
                ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
                ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
                ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
                TF_VAR_azure_subscription_id: ${{ vars.ARM_SUBSCRIPTION_ID }}
                TF_VAR_azure_client_id: ${{ vars.ARM_CLIENT_ID }}
                TF_VAR_image_name: ${{ vars.IMAGE_NAME }}
              run: terraform plan

            - name: Approve Terraform Plan
              uses: trstringer/manual-approval@v1
              with:
                secret: ${{ github.token }}
                approvers: dppick2solutions

            - name: Terraform Apply
              env:
                ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
                ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
                ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
                TF_VAR_azure_subscription_id: ${{ vars.ARM_SUBSCRIPTION_ID }}
                TF_VAR_azure_client_id: ${{ vars.ARM_CLIENT_ID }}
                TF_VAR_image_name: ${{ vars.IMAGE_NAME }}
              run: terraform apply -auto-approve